YlPlusProject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("__debug__/", include("debug_toolbar.urls")),
    path("", include("homepage.urls")),
    path("group/", include("group.urls")),
    path("rating/", include("rating.urls")),
    path("theatres/", include("theatres.urls")),
    path("auth/", include("users.urls")),
    path("auth/", include("django.contrib.auth.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

group/urls.py
from django.urls import include, path

from group.views import GroupCreateView, GroupDetailView, GroupListView

app_name = "group"
urlpatterns = [
    path("", GroupListView.as_view(), name="group_list"),
    path("<int:id>/", GroupDetailView.as_view(), name="group_detail"),
    path("create/", GroupCreateView.as_view(), name="group_create"),
    path("__debug__/", include("debug_toolbar.urls")),
]

rating/urls.py
from django.urls import include, path

from rating.views import RatingCreateView, RatingTheatreView

app_name = "rating"
urlpatterns = [
    path("theatre/<int:id>/", RatingTheatreView.as_view(), name="rating_theatre"),
    path("create/<str:type>/<int:id>/", RatingCreateView.as_view(), name="rating_create"),
    path("__debug__/", include("debug_toolbar.urls")),
]

theatres/urls.py
from django.urls import include, path

from theatres.views import (
    ActorCreateView,
    EventCreateView,
    EventDetailView,
    EventListView,
    TheatresCreateView,
    TheatresDetailView,
    TheatresListView,
)

app_name = "theatres"
urlpatterns = [
    path("", TheatresListView.as_view(), name="theatres_list"),
    path("<int:id>/", TheatresDetailView.as_view(), name="theatres_detail"),
    path("create/", TheatresCreateView.as_view(), name="theatres_create"),
    path("events/", EventListView.as_view(), name="events_list"),
    path("events/<int:id>/", EventDetailView.as_view(), name="events_detail"),
    path("events/create/", EventCreateView.as_view(), name="events_create"),
    path("actors/create/", ActorCreateView.as_view(), name="actors_create"),
    path("__debug__/", include("debug_toolbar.urls")),
]

users/urls.py
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordChangeDoneView,
    PasswordChangeView,
    PasswordResetCompleteView,
    PasswordResetConfirmView,
    PasswordResetDoneView,
    PasswordResetView,
)
from django.urls import include, path

from users.views import ActorProfileView, ProfileView, SignupView, UserDetailView

app_name = "users"
urlpatterns = [
    path("login/", LoginView.as_view(template_name="users/login.html"), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path(
        "password_change/",
        PasswordChangeView.as_view(template_name="users/password_change.html"),
        name="password_change",
    ),
    path(
        "password_change/done/",
        PasswordChangeDoneView.as_view(template_name="users/password_change_done.html"),
        name="password_change_done",
    ),
    path(
        "password_reset/", PasswordResetView.as_view(template_name="users/password_reset.html"), name="password_reset"
    ),
    path(
        "password_reset/done/",
        PasswordResetDoneView.as_view(template_name="users/password_reset_done.html"),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(template_name="users/password_reset_confirm.html"),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        PasswordResetCompleteView.as_view(template_name="users/password_reset_complete.html"),
        name="password_reset_complete",
    ),
    path("profile/", ProfileView.as_view(), name="profile"),
    path("signup/", SignupView.as_view(), name="signup"),
    path("actors/<int:id>", ActorProfileView.as_view(), name="actor_profile"),
    path("users/<int:id>/", UserDetailView.as_view(), name="users_detail"),
    path("__debug__/", include("debug_toolbar.urls")),
]

theatres/models.py
from django.db import models

from core.models import (
    ContactsGroup,
    GalleryBaseModel,
    ImageBaseModel,
    Location,
    PublishedBaseModel,
)
from rating.models import ReviewGroup
from theatres.querysets import EventQuerySet, TheatreQuerySet, TroupeMemberQuerySet


class Troupe(models.Model):
    class Meta:
        verbose_name = "Труппа"
        verbose_name_plural = "Труппы"


class TroupeMember(models.Model):
    troupe = models.ForeignKey(Troupe, verbose_name="Труппа", related_name="members", on_delete=models.CASCADE)
    profile = models.ForeignKey(
        to="users.ActorProfile", verbose_name="Профиль", on_delete=models.CASCADE, related_name="troupe_members"
    )
    role = models.CharField(verbose_name="Роль", max_length=100, null=True, blank=True)

    objects = models.Manager()
    troupe_members = TroupeMemberQuerySet.as_manager()

    class Meta:
        verbose_name = "Участник труппы"
        verbose_name_plural = "Участники трупп"


class Theatre(PublishedBaseModel, ImageBaseModel):
    name = models.CharField("Название", max_length=150)
    description = models.CharField("Описание", max_length=2500, null=True, blank=True)
    location = models.ForeignKey(Location, verbose_name="Местоположение", on_delete=models.CASCADE)
    troupe = models.ForeignKey(Troupe, verbose_name="Труппа", on_delete=models.SET_NULL, null=True, blank=True)
    reviews = models.ForeignKey(ReviewGroup, verbose_name="Отзывы", on_delete=models.SET_NULL, null=True, blank=True)
    contacts = models.ForeignKey(
        ContactsGroup, verbose_name="Контакты", on_delete=models.SET_NULL, null=True, blank=True
    )

    objects = models.Manager()
    theatres = TheatreQuerySet.as_manager()

    class Meta:
        verbose_name = "Театр"
        verbose_name_plural = "Театры"

    def __str__(self):
        return self.name


class ModerationTheatre(Theatre):
    class Meta:
        verbose_name = "Театр на модерации"
        verbose_name_plural = "Театры на модерации"
        proxy = True


class TheatreImage(GalleryBaseModel):
    theatre = models.ForeignKey(Theatre, on_delete=models.CASCADE, related_name="gallery_images")


class Event(PublishedBaseModel, ImageBaseModel):
    name = models.CharField("Название", max_length=150)
    description = models.CharField("Описание", max_length=2500, null=True, blank=True)
    theatre = models.ForeignKey(Theatre, verbose_name="Театр", on_delete=models.CASCADE, related_name="events")
    troupe = models.ForeignKey(Troupe, verbose_name="Труппа", on_delete=models.SET_NULL, null=True, blank=True)
    reviews = models.ForeignKey(ReviewGroup, verbose_name="Отзывы", on_delete=models.SET_NULL, null=True, blank=True)

    objects = models.Manager()
    events = EventQuerySet.as_manager()

    class Meta:
        verbose_name = "Событие"
        verbose_name_plural = "События"

    def __str__(self):
        return self.name


class ModerationEvent(Event):
    class Meta:
        verbose_name = "Событие на модерации"
        verbose_name_plural = "События на модерации"
        proxy = True


class EventImage(GalleryBaseModel):
    event = models.ForeignKey(Event, on_delete=models.CASCADE, related_name="gallery_images")

theatres/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.views import View
from django.views.generic import FormView, TemplateView

from core.forms import SearchForm
from core.models import City, ContactType
from rating.models import ReviewRating
from theatres.forms import ActorForm, EventForm, TheatreForm
from theatres.models import Event, Theatre, TroupeMember
from users.models import ActorProfile


class TheatresListView(FormView):
    template_name = "theatres/theatres_list.html"
    form_class = SearchForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        search_query = kwargs.get("search_query", None)
        location_query = kwargs.get("location_query", None)

        if search_query or location_query:
            context["theatres"] = Theatre.theatres.theatre_search(search_query, location_query)
            context["current_search"] = search_query
            context["current_select"] = int(location_query)
        else:
            context["theatres"] = Theatre.theatres.theatres_list()
        context["cities"] = City.objects.all()

        return context

    def form_valid(self, form, **kwargs):
        return self.render_to_response(
            context=self.get_context_data(search_query=form.data["search"], location_query=form.data["location"])
        )


class TheatresDetailView(TemplateView):
    template_name = "theatres/theatres_detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context["theatre"] = get_object_or_404(Theatre.theatres.theatre_details(kwargs["id"]))
        context["actors"] = TroupeMember.objects.filter(
            troupe=context["theatre"].troupe, profile__is_published=True
        ).prefetch_related("profile")

        return context


class TheatresCreateView(LoginRequiredMixin, TemplateView):
    template_name = "theatres/theatres_create.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context["form"] = TheatreForm()
        context["actors"] = ActorProfile.objects.filter(is_published=True)

        return context

    def post(self, request, *args, **kwargs):
        form = TheatreForm(request.POST, request.FILES, fields=request.POST.get("field_count"))

        if not form.is_valid():
            return self.render_to_response(context=dict(self.get_context_data(), form=form))
        form.save()

        return redirect("theatres:theatres_list")


class EventListView(FormView):
    template_name = "theatres/events_list.html"
    form_class = SearchForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        search_query = kwargs.get("search_query", None)
        location_query = kwargs.get("location_query", None)

        if search_query or location_query:
            context["events"] = Event.events.event_search(search_query, location_query)
            context["current_search"] = search_query
            context["current_select"] = int(location_query)
        else:
            context["events"] = Event.events.events_list()
        context["cities"] = City.objects.all()

        return context

    def form_valid(self, form, **kwargs):
        return self.render_to_response(
            context=self.get_context_data(search_query=form.data["search"], location_query=form.data["location"])
        )


class EventDetailView(View):
    def get(self, request, **kwargs):
        template = "theatres/events_detail.html"
        user = request.user

        reviews = get_object_or_404(Event.events.event_ratings(kwargs["id"]))
        event = get_object_or_404(Event.events.event_details(kwargs["id"]))

        for review in reviews.reviews.reviews.all():
            review.user_like = user in [review.user for review in review.like]
            review.user_dislike = user in [review.user for review in review.dislike]

        return render(
            request,
            template,
            {
                "reviews": reviews,
                "event": event,
                "actors": TroupeMember.objects.filter(troupe=event.troupe).prefetch_related("profile"),
            },
        )

    @staticmethod
    def post(request, **kwargs):
        review_id = int(request.POST.get("id"))
        like = request.POST.get("like") == "True"
        review = ReviewRating.objects.filter(review_id=review_id).first()

        json_file = {
            "like": like,
            "like_num": int(request.POST.get("like_num")),
            "dislike_num": int(request.POST.get("dislike_num")),
        }

        if review and review.star == like:
            review.delete()
        else:
            ReviewRating.objects.update_or_create(
                user_id=request.user.id,
                review_id=review_id,
                defaults={"star": like},
            )

        return JsonResponse(json_file)


class ActorCreateView(LoginRequiredMixin, TemplateView):
    template_name = "theatres/actors_create.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context["form"] = ActorForm()
        context["contacts"] = ContactType.objects.all()
        context["id"] = kwargs.get("id")

        return context

    def post(self, request, *args, **kwargs):
        form = ActorForm(request.POST, request.FILES, fields=request.POST.get("field_count"))

        if not form.is_valid():
            return self.render_to_response(context=dict(self.get_context_data(), form=form))
        form.save()

        return redirect("homepage:home")


class EventCreateView(LoginRequiredMixin, TemplateView):
    template_name = "theatres/events_create.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context["form"] = EventForm()
        context["actors"] = ActorProfile.objects.filter(is_published=True)

        return context

    def post(self, request, *args, **kwargs):
        form = EventForm(request.POST, request.FILES, fields=request.POST.get("field_count"))

        if not form.is_valid():
            return self.render_to_response(context=dict(self.get_context_data(), form=form))
        form.save()

        return redirect("theatres:events_list")

templates/theatres/events_detail.html
{% extends "base.html" %}
{% load static %}
{% block title %}Постановка{% endblock %}
{% block content %}
    <section>
        <div data-bss-parallax-bg="true" style="height: 600px;background-image: url({% if event.image %} {{event.image.url}} {% else %} {% static '/img/NoneEvent400x300.jpg' %} {% endif %} );background-position: center;background-size: cover;">
            <div class="container h-100">
                <div class="row h-100">
                    <div class="col-md-6 text-center text-md-start d-flex d-sm-flex d-md-flex justify-content-center align-items-center justify-content-md-start align-items-md-center justify-content-xl-center">
                        <div style="max-width: 320px;">
                            <h1 class="text-uppercase fw-bold text-white">{{ event.name }}</h1>
                            {% if event.description %}
                                <p class="my-3 text-white">{{ event.description | truncatewords:10 }}</p>
                            {% endif %}
                            <a class="btn btn-primary btn-lg me-2 menu_sub_link menu_linked" role="button" style="margin-top: 9px;" data-goto=".events">Место проведения</a>
                            {% if actors %}
                            <a class="btn btn-primary btn-lg menu_sub_link menu_linked" type="button" style="margin-top: 9px;" data-goto=".actors">Актёры</a>
                            {% endif %}
                            {% if event.description %}
                                <a class="btn btn-primary btn-lg me-2 menu_sub_link menu_linked" role="button" style="margin-top: 9px;" data-goto=".description">Описание</a>
                            {% endif %}
                            <a class="btn btn-primary btn-lg menu_sub_link menu_linked" type="button" style="margin-top: 9px;" data-goto=".ratings">Отзывы</a>
                            <a class="btn btn-outline-primary btn-lg menu_sub_link menu_linked" role="button" style="margin-top: 9px;" href="{% url 'rating:rating_create' 'event' reviews.id %}">Оставить отзыв</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <section>
        <div class="container py-4 py-xl-5">
            <div class="text-center text-white-50 bg-primary border rounded border-0 p-3">
                <div class="row row-cols-2 row-cols-md-2">
                    <div class="col">
                        <div class="p-3">
                            <h4 class="display-5 fw-bold text-white mb-0"><i class="far fa-edit"></i>{{event.reviews_count }}</h4>
                            <p class="mb-0">Отзывов на данную постановку</p>
                        </div>
                    </div>
                    <div class="col">
                        <div class="p-3">
                            <h4 class="display-5 fw-bold text-white mb-0"><i class="far fa-star"></i>{% if event.reviews_average_score %}{{ event.reviews_average_score|floatformat:1 }}{% else %}0,0{% endif %}</h4>
                            <p class="mb-0">Средний рейтинг по 5 бальной шкале</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <section>
        {% include 'includes/description_block.html' with description=event.description only %}
        <h2 class="text-center events">Место проведения</h2>
        <div class="container py-5">
            <div class="row row-cols-1 row-cols-md-2 mx-auto" style="max-width: 900px;">
                <div class="col mb-5">
                    {% if event.theatre.image %}
                        <img class="rounded img-fluid shadow" src="{{ event.theatre.get_image_400x300.url}}">
                    {% else %}
                        <img class="rounded img-fluid shadow" src="{% static 'img/NoneTheatre400x300.jpg' %}">
                    {% endif %}
                </div>
                <div class="col d-md-flex align-items-md-end align-items-lg-center mb-5">
                    {% include 'includes/theatre_block.html' with theatre=event.theatre only %}
                </div>
            </div>
        </div>
        {% if actors %}
            {% include 'includes/actors_block.html' with actors=actors only %}
        {% endif %}
        <h2 class="text-center ratings">Отзывы</h2>
        <div class="album py-5">
        <div class="container">
        {% if reviews.reviews.reviews.exists %}
            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-2 g-3 ">
                {% for review in reviews.reviews.reviews.all %}
                <div class="card card-inner mx-auto">
                    <div class="card-body">
                        <div class="row">
                            <div class="row-md mb-2">
                                <a href="{% if review.user.id != request.user.id %} {% url 'users:users_detail' review.user.id %} {% else %} {% url 'users:profile' %} {% endif %}">
                                    <img class="border rounded-circle img-profile" style="border:2px solid {{ review.user.user_profile.rank.color }}!important" src="{% if review.user.user_profile.image %} {{ review.user.user_profile.get_image_400x300.url }} {% else %} {% static '/img/NoneUser.jpg' %} {% endif %}">
                                    <span class="d-none d-lg-inline me-2 text-gray-600 small">{{ review.user.username }}</span>
                                </a>
                            </div>
                            <div>
                                <div class="form-group">
                                    <div class="star-rating mb-3">
                                        <div class="star-rating__wrap">
                                            {% if review.star == 5 %}
                                                <label class="fa fa-star fa-lg cool-star"></label>
                                                <label class="fa fa-star fa-lg cool-star"></label>
                                                <label class="fa fa-star fa-lg cool-star"></label>
                                                <label class="fa fa-star fa-lg cool-star"></label>
                                                <label class="fa fa-star fa-lg cool-star"></label>
                                            {% elif review.star == 4 %}
                                                <label class="fa fa-star-o fa-lg cool-star"></label>
                                                <label class="fa fa-star fa-lg cool-star"></label>
                                                <label class="fa fa-star fa-lg cool-star"></label>
                                                <label class="fa fa-star fa-lg cool-star"></label>
                                                <label class="fa fa-star fa-lg cool-star"></label>
                                            {% elif review.star == 3 %}
                                                <label class="fa fa-star-o fa-lg cool-star"></label>
                                                <label class="fa fa-star-o fa-lg cool-star"></label>
                                                <label class="fa fa-star fa-lg cool-star"></label>
                                                <label class="fa fa-star fa-lg cool-star"></label>
                                                <label class="fa fa-star fa-lg cool-star"></label>
                                            {% elif review.star == 2 %}
                                                <label class="fa fa-star-o fa-lg cool-star"></label>
                                                <label class="fa fa-star-o fa-lg cool-star"></label>
                                                <label class="fa fa-star-o fa-lg cool-star"></label>
                                                <label class="fa fa-star fa-lg cool-star"></label>
                                                <label class="fa fa-star fa-lg cool-star"></label>
                                            {% elif review.star == 1 %}
                                                <label class="star-rating__ico fa fa-star-o fa-lg cool-star"></label>
                                                <label class="star-rating__ico fa fa-star-o fa-lg cool-star"></label>
                                                <label class="star-rating__ico fa fa-star-o fa-lg cool-star"></label>
                                                <label class="star-rating__ico fa fa-star-o fa-lg cool-star"></label>
                                                <label class="star-rating__ico fa fa-star fa-lg cool-star"></label>
                                            {% endif %}
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <form class="row-md-9" action="." class="like-form" method="post">
                                {% csrf_token %}
                                <p>{{ review.content }}</p>
                                <input hidden name="id" value="{{ review.id }}">
                                <input hidden id="like_num" name="like_num" value="{{ review.like|length }}">
                                <input hidden id="dislike_num" name="dislike_num" value="{{ review.dislike|length }}">
                                <p id="like-div">
                                    {% if review.user_like%}
                                        <button type="button" onclick="postLike(this)" id="like" name="like" value="True" class="btn btn-primary like">
                                            <i class="fa fa-thumbs-up" aria-hidden="true"></i> {{ review.like|length }}
                                        </button>
                                    {% else %}
                                        <button type="button" onclick="postLike(this)" id="like" name="like" value="True" class="btn btn-light like">
                                            <i class="fa fa-thumbs-o-up" aria-hidden="true"> </i> {{ review.like|length }}
                                        </button>
                                    {% endif %}
                                    {% if review.user_dislike%}
                                        <button type="button" onclick="postLike(this)" id="dislike" name="like" value="False" class="btn btn-danger like">
                                            <i class="fa fa-thumbs-down" aria-hidden="true"></i> {{ review.dislike|length }}
                                        </button>
                                    {% else %}
                                        <button type="button" onclick="postLike(this)" id="dislike" name="like" value="False" class="btn btn-light like">
                                            <i class="fa fa-thumbs-o-down" aria-hidden="true"> </i> {{ review.dislike|length }}
                                        </button>
                                    {% endif %}
                               </p>
                            </form>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        {% else %}
            <h4>Отзывы отсутствуют.</h4>
        {% endif %}
        </div>
        </div>
        <div class="simple-slider mb-5">
            <h2 class="text-center">Галерея</h2>
            {% if event.gallery_images.all %}
            <div class="swiper-container">
                <div class="swiper-wrapper">
                    {% for image in event.gallery_images.all %}
                        <div class="swiper-slide" style="background: url(&quot;{{ image.get_image_1400x800.url }}&quot;) center center / cover no-repeat;"></div>
                    {% endfor %}
                </div>
                <div class="swiper-pagination"></div>
                <div class="swiper-button-prev"></div>
                <div class="swiper-button-next"></div>
            </div>
            {% else %}
                <h2 class="text-center">Дополнительных картинок нет.</h2>
            {% endif %}
        </div>
    </section>
{% endblock %}

templates/theatres/events_list.html
{% extends "base.html" %}
{% block title %}Постановки{% endblock %}
{% load static %}
{% block content %}
    <section>
        <div class="container py-5">
            <div class="row mb-4 mb-lg-5">
                <div class="col-md-8 col-xl-6 text-center mx-auto">
                    <h3 class="fw-bold">Поиск постановок</h3>
                    <form class="d-flex justify-content-center flex-wrap my-2" method="post" action=".">
                        {% csrf_token %}
                        <div class="my-2"><input class="form-control" type="text" name="search" placeholder="Название постановки" value="{{ current_search }}"></div>
                        <div class="my-2"><button class="btn btn-primary ms-sm-2" type="submit">Поиск</button></div>
                        <div style="padding-top: 6px;">
                            <label class="form-label text-nowrap ms-sm-2">Город&nbsp;&nbsp;
                                <select name="location" class="form-select d-inline-block form-select form-select-sm">
                                        <option value="" selected="">---------</option>
                                        {% for city in cities %}
                                            <option value="{{city.id}}" {% if current_select == city.id %} selected {% endif %}>{{ city.name }}</option>
                                        {% endfor %}
                                </select>
                            </label>
                        </div>
                    </form>
                </div>
            </div>
            {% for event in events %}
                <div class="row row-cols-1 row-cols-md-2 mx-auto" style="max-width: 900px;">
                    <div class="col mb-5">
                        {% if event.image %}
                            <img class="rounded img-fluid shadow" src="{{ event.get_image_400x300.url}}">
                        {% else %}
                            <img class="rounded img-fluid shadow" src="{% static 'img/NoneEvent400x300.jpg' %}">
                        {% endif %}
                    </div>
                    <div class="col d-md-flex align-items-md-end align-items-lg-center mb-5">
                        <div>
                            <h5 class="fw-bold">{{ event.name }}</h5>
                            {% if event.description %}
                                <p>{{ event.description | truncatewords:10 }}</p>
                            {% endif %}
                            <p class="text-muted mb-4"><i class="fas fa-map-marker-alt" style="padding-right: 8px;"></i>{{ event.theatre.location.query }}
                            <br><i class="fas fa-university" style="padding-right: 4px;"></i>{{ event.theatre }}</p>
                            <a href="{% url 'theatres:events_detail' event.id %}" class="btn btn-primary shadow" type="button">Больше</a>
                        </div>
                    </div>
                </div>
            {% empty %}
                <h3 class="fw-bold text-center">Постановки отсутствуют</h3>
            {% endfor %}
        </div>
        <section class="py-4 py-xl-5">
            <div class="container">
                <div class="text-white bg-dark border rounded border-0 p-4 p-md-5">
                    <h2 class="fw-bold text-white mb-3">Не нашли нужную постановку? Не беда, добавьте её!</h2>
                    <p class="mb-4">После заполнения информации о новой постановке она отправится на модерацию. После её прохождения она будет добавлена в общий список.</p><a class="btn btn-primary btn-lg me-2" role="button" href="{% url 'theatres:events_create' %}">Приступить к созданию</a>
                </div>
            </div>
        </section>
    </section>
{% endblock %}