YlPlusProject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("__debug__/", include("debug_toolbar.urls")),
    path("", include("homepage.urls")),
    path("group/", include("group.urls")),
    path("rating/", include("rating.urls")),
    path("theatres/", include("theatres.urls")),
    path("auth/", include("users.urls")),
    path("auth/", include("django.contrib.auth.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

group/urls.py
from django.urls import include, path

from group.views import GroupCreateView, GroupDetailView, GroupListView

app_name = "group"
urlpatterns = [
    path("", GroupListView.as_view(), name="group_list"),
    path("<int:id>/", GroupDetailView.as_view(), name="group_detail"),
    path("create/", GroupCreateView.as_view(), name="group_create"),
    path("__debug__/", include("debug_toolbar.urls")),
]

homepage/urls.py
from django.urls import include, path

from homepage.views import HomeView

app_name = "homepage"
urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("__debug__/", include("debug_toolbar.urls")),
]

theatres/urls.py
from django.urls import include, path

from theatres.views import (
    ActorCreateView,
    EventCreateView,
    EventDetailView,
    EventListView,
    TheatresCreateView,
    TheatresDetailView,
    TheatresListView,
)

app_name = "theatres"
urlpatterns = [
    path("", TheatresListView.as_view(), name="theatres_list"),
    path("<int:id>/", TheatresDetailView.as_view(), name="theatres_detail"),
    path("create/", TheatresCreateView.as_view(), name="theatres_create"),
    path("events/", EventListView.as_view(), name="events_list"),
    path("events/<int:id>/", EventDetailView.as_view(), name="events_detail"),
    path("events/create/", EventCreateView.as_view(), name="events_create"),
    path("actors/create/", ActorCreateView.as_view(), name="actors_create"),
    path("__debug__/", include("debug_toolbar.urls")),
]

users/urls.py
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordChangeDoneView,
    PasswordChangeView,
    PasswordResetCompleteView,
    PasswordResetConfirmView,
    PasswordResetDoneView,
    PasswordResetView,
)
from django.urls import include, path

from users.views import ActorProfileView, ProfileView, SignupView, UserDetailView

app_name = "users"
urlpatterns = [
    path("login/", LoginView.as_view(template_name="users/login.html"), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path(
        "password_change/",
        PasswordChangeView.as_view(template_name="users/password_change.html"),
        name="password_change",
    ),
    path(
        "password_change/done/",
        PasswordChangeDoneView.as_view(template_name="users/password_change_done.html"),
        name="password_change_done",
    ),
    path(
        "password_reset/", PasswordResetView.as_view(template_name="users/password_reset.html"), name="password_reset"
    ),
    path(
        "password_reset/done/",
        PasswordResetDoneView.as_view(template_name="users/password_reset_done.html"),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(template_name="users/password_reset_confirm.html"),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        PasswordResetCompleteView.as_view(template_name="users/password_reset_complete.html"),
        name="password_reset_complete",
    ),
    path("profile/", ProfileView.as_view(), name="profile"),
    path("signup/", SignupView.as_view(), name="signup"),
    path("actors/<int:id>", ActorProfileView.as_view(), name="actor_profile"),
    path("users/<int:id>/", UserDetailView.as_view(), name="users_detail"),
    path("__debug__/", include("debug_toolbar.urls")),
]

templates/includes/actor_block.html
<div>
    <h5 class="fw-bold">{{ actor.profile.first_name }} {{ actor.profile.last_name }}</h5>
    {% if actor.profile.description %}
        <p>{{ actor.profile.description | truncatewords:10 }}</p>
    {% else %}
        <p class="text-muted">Описание отсутствует</p>
    {% endif %}
    <p class="text-muted mb-4">
        {% if actor.role %}
            <i class="fa fa-user"></i>&nbsp;Роль: {{ actor.role }}
        {% endif %}
    </p>
</div>

templates/includes/actors_block.html
{% load static %}

<div class="hobbies group actors" style="padding-right: 15vh;padding-left: 15vh;padding-top: 0vh;padding-bottom: 4vh;">
    <h2 class="text-center">Актёры</h2>
    <div class="album py-5">
    <div class="container">
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
    {% for actor in actors %}
    <div class="col">
        <div class="card shadow sm text-center">
            <div class="col mb-5 ">
                <a href="{% url 'users:actor_profile' actor.profile.id %}"><img class="rounded img-fluid shadow" src="{% if actor.profile.image %} {{ actor.profile.get_image_400x300.url }} {% else %} {% static '/img/NoneUser400x300.jpg' %} {% endif %}"></a>
            </div>
            <div class="col d-md-flex mx-auto align-items-md-end align-items-lg-center mb-2">
                {% include 'includes/actor_block.html' with actor=actor only %}
            </div>
        </div>
    </div>
    {% endfor %}
    </div>
    </div>
    </div>
</div>

templates/includes/description_block.html
<h2 class="text-center description">Полное описание</h2>
<div class="container py-5">
    {% if description %}
        {{ description }}
    {% else %}
        <h4>Описание отсутствует.</h4>
    {% endif %}
</div>

templates/includes/footer.html
<footer class="text-center bg-dark mt-auto">
    <div class="container text-white py-4 py-lg-5">
        <ul class="list-inline">
            <li class="list-inline-item me-4"><a class="link-light" href="https://vk.com/nytrock">Исправить неточность</a></li>
            <li class="list-inline-item me-4"><a class="link-light" href="https://t.me/fohan">Предложения по улучшению</a></li>
            <li class="list-inline-item"><a class="link-light" href="https://github.com/Jubastik/YlPlusProject">GitHub</a></li>
        </ul>
        <p class="text-muted mb-0">Copyright © 2022 Великие джангисты</p>
    </div>
</footer>

templates/includes/form-errors.html
{% if form.errors %}
    {% for field in form%}
        {% for error in field.errors %}
            {{ error|escape }}
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        {{ error|escape }}
    {% endfor %}
{% endif %}

templates/includes/form-login.html
{% csrf_token %}

 {% for field in form%}
    <div class="form-floating">
      {% if not field.field.widget.input_type or field.field.widget.input_type == "select" %}
        {{ field }}
      {% else %}
        <input type="{{ field.field.widget.input_type }}" name="{{ field.html_name }}" class="form-control" id="{{ field.id_for_label }}" {% if field.field.widget.input_type == "number"%} max="{{ field.field.max_value }}" min="{{ field.field.min_value }}" {% endif %} placeholder="Password">
      {% endif %}
      <label for="{{ field.id_for_label }}">
        {{ field.label }}
        {% if field.field.required %}
            <span>*</span>
        {% endif %}
    </label>
    </div>
{% endfor %}

templates/includes/header.html
{% load static %}
<header class="navbar navbar-light navbar-expand-md navbar-fixed-top navigation-clean-button" style="background: rgb(34, 34, 34);border-radius: 20;border-top-left-radius: 20;border-top-right-radius: 20;border-bottom-right-radius: 20;border-bottom-left-radius: 20;border-style: none;padding-bottom: 10px;padding-top: 15px;">
    <div class="container"><button data-bs-toggle="collapse" class="navbar-toggler" data-bs-target="#navcol-1"><span class="visually-hidden">Toggle navigation</span><span class="navbar-toggler-icon"></span></button>
        <div><a class="navbar-brand" href="{% url 'homepage:home' %}"><span>Tredio</span> </a></div>
        <div class="collapse navbar-collapse" id="navcol-1" style="color: rgb(255,255,255);">
            <ul class="navbar-nav nav-right">
                <li class="nav-item"></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'theatres:theatres_list' %}" style="color: rgba(224,217,217,0.9);">Театры</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'theatres:events_list' %}" style="color: rgba(224,217,217,0.9);">Постановки</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'group:group_list' %}" style="color: rgba(224,217,217,0.9);">Встречи</a></li>
            </ul>


            <p class="ms-auto navbar-text actions">
                {% if not request.user.is_authenticated %}
                    <a class="login" href="{% url 'login' %}" style="color: rgba(224,217,217,0.9);">Вход</a>
                    <a class="btn btn-light action-button" role="button" href="{% url 'users:signup' %}" style="color: rgba(0,0,0,0.9);background: var(--bs-gray-200);border-radius: 10px;border-style: solid;border-color: rgba(0,0,0,0.9);font-size: 16px;padding: 5px 8px;">Регистрация</a>
                {% endif %}
            </p>
            {% if request.user.is_authenticated  %}
                <div class="dropdown no-arrow">
                    <a class="dropdown-toggle nav-link" aria-expanded="false" data-bs-toggle="dropdown" href="#">
                        <span class="d-none d-lg-inline me-2 text-gray-600 small">{{ request.user.username }}</span>
                        <img class="rounded-circle img-profile" style="border:2px solid {{ profile_header.rank.color }}" src="{% if profile_header.image %} {{ profile_header.get_image_400x300.url }} {% else %} {% static '/img/NoneUser.jpg' %} {% endif %}">
                    </a>
                    <div class="dropdown-menu shadow dropdown-menu-end animated--grow-in">
                        <a class="dropdown-item" href="{% url 'users:profile' %}">
                            <i class="fas fa-user fa-sm fa-fw me-2 text-gray-400"></i>&nbsp;Профиль
                        </a>
                        {% if request.user.is_superuser %}
                        <a class="dropdown-item" href="/admin/">
                            <i class="fas fa-cogs fa-sm fa-fw me-2 text-gray-400"></i>&nbsp;Админка
                        </a>
                        {% endif %}
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'logout' %}">
                            <i class="fas fa-sign-out-alt fa-sm fa-fw me-2 text-gray-400"></i>&nbsp;Выйти
                        </a>
                    </div>
                </div>
            {% endif %}
        </div>
    </div>
</header>

templates/includes/theatre_block.html
<div>
    <h5 class="fw-bold">{{  theatre.name }}</h5>
    {% if theatre.description %}
        <p>{{  theatre.description | truncatewords:10}}</p>
    {% endif %}
    <p class="text-muted mb-4"><i class="fas fa-map-marker-alt" style="padding-right: 8px;"></i>{{  theatre.location.query }}</p>
    <a href="{% url 'theatres:theatres_detail' theatre.id %}" class="btn btn-primary shadow" type="button">Больше</a>
</div>