YlPlusProject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("__debug__/", include("debug_toolbar.urls")),
    path("", include("homepage.urls")),
    path("group/", include("group.urls")),
    path("rating/", include("rating.urls")),
    path("theatres/", include("theatres.urls")),
    path("auth/", include("users.urls")),
    path("auth/", include("django.contrib.auth.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

group/urls.py
from django.urls import include, path

from group.views import GroupCreateView, GroupDetailView, GroupListView

app_name = "group"
urlpatterns = [
    path("", GroupListView.as_view(), name="group_list"),
    path("<int:id>/", GroupDetailView.as_view(), name="group_detail"),
    path("create/", GroupCreateView.as_view(), name="group_create"),
    path("__debug__/", include("debug_toolbar.urls")),
]

theatres/urls.py
from django.urls import include, path

from theatres.views import (
    ActorCreateView,
    EventCreateView,
    EventDetailView,
    EventListView,
    TheatresCreateView,
    TheatresDetailView,
    TheatresListView,
)

app_name = "theatres"
urlpatterns = [
    path("", TheatresListView.as_view(), name="theatres_list"),
    path("<int:id>/", TheatresDetailView.as_view(), name="theatres_detail"),
    path("create/", TheatresCreateView.as_view(), name="theatres_create"),
    path("events/", EventListView.as_view(), name="events_list"),
    path("events/<int:id>/", EventDetailView.as_view(), name="events_detail"),
    path("events/create/", EventCreateView.as_view(), name="events_create"),
    path("actors/create/", ActorCreateView.as_view(), name="actors_create"),
    path("__debug__/", include("debug_toolbar.urls")),
]

users/urls.py
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordChangeDoneView,
    PasswordChangeView,
    PasswordResetCompleteView,
    PasswordResetConfirmView,
    PasswordResetDoneView,
    PasswordResetView,
)
from django.urls import include, path

from users.views import ActorProfileView, ProfileView, SignupView, UserDetailView

app_name = "users"
urlpatterns = [
    path("login/", LoginView.as_view(template_name="users/login.html"), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path(
        "password_change/",
        PasswordChangeView.as_view(template_name="users/password_change.html"),
        name="password_change",
    ),
    path(
        "password_change/done/",
        PasswordChangeDoneView.as_view(template_name="users/password_change_done.html"),
        name="password_change_done",
    ),
    path(
        "password_reset/", PasswordResetView.as_view(template_name="users/password_reset.html"), name="password_reset"
    ),
    path(
        "password_reset/done/",
        PasswordResetDoneView.as_view(template_name="users/password_reset_done.html"),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(template_name="users/password_reset_confirm.html"),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        PasswordResetCompleteView.as_view(template_name="users/password_reset_complete.html"),
        name="password_reset_complete",
    ),
    path("profile/", ProfileView.as_view(), name="profile"),
    path("signup/", SignupView.as_view(), name="signup"),
    path("actors/<int:id>", ActorProfileView.as_view(), name="actor_profile"),
    path("users/<int:id>/", UserDetailView.as_view(), name="users_detail"),
    path("__debug__/", include("debug_toolbar.urls")),
]

group/models.py
from django.contrib.auth import get_user_model
from django.core.validators import MinValueValidator
from django.db import models

from group.querysets import MeetupParticipantQuerySet, MeetupQuerySet
from theatres.models import Event

User = get_user_model()


class Meetup(models.Model):
    host = models.ForeignKey(User, verbose_name="Организатор", on_delete=models.CASCADE, related_name="meetups")
    event = models.ForeignKey(Event, verbose_name="Событие", on_delete=models.CASCADE, related_name="meetups")
    start = models.DateTimeField(verbose_name="Время встречи")
    participants_limit = models.IntegerField(
        "Максимальное кол-во участников", validators=[MinValueValidator(1)], null=True, blank=True
    )
    description = models.CharField("Описание", max_length=2500, null=True, blank=True)

    objects = models.Manager()
    meetups = MeetupQuerySet.as_manager()

    def is_participant(self, user: User):
        return (
            user == self.host or MeetupParticipant.meetup_participants.fetch_by_meetup(self).filter(user=user).exists()
        )

    class Meta:
        verbose_name = "Встреча"
        verbose_name_plural = "Встречи"


class MeetupParticipant(models.Model):
    meetup = models.ForeignKey(Meetup, verbose_name="Встреча", related_name="participants", on_delete=models.CASCADE)
    user = models.ForeignKey(User, verbose_name="Участник", on_delete=models.CASCADE)

    objects = models.Manager()
    meetup_participants = MeetupParticipantQuerySet.as_manager()

    class Meta:
        verbose_name = "Участник встречи"
        verbose_name_plural = "Участники встреч"

group/forms.py
from django.forms import ModelForm, widgets

from group.models import Meetup
from theatres.models import Event


class MeetupForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(MeetupForm, self).__init__(*args, **kwargs)
        self.fields[Meetup.event.field.name].queryset = Event.objects.filter(is_published=True)

    class Meta:
        model = Meetup
        fields = (
            Meetup.event.field.name,
            Meetup.start.field.name,
            Meetup.description.field.name,
            Meetup.participants_limit.field.name,
        )
        widgets = {
            Meetup.event.field.name: widgets.Select(attrs={"class": "multi-form-input"}),
            Meetup.start.field.name: widgets.DateTimeInput(
                attrs={"class": "multi-form-input", "type": "datetime-local"}
            ),
            Meetup.description.field.name: widgets.Textarea(attrs={"class": "multi-form-input"}),
            Meetup.participants_limit.field.name: widgets.NumberInput(attrs={"class": "multi-form-input"}),
        }

        labels = {
            Meetup.event.field.name: "Постановка",
            Meetup.start.field.name: "Дата встречи",
            Meetup.description.field.name: "Описание",
            Meetup.participants_limit.field.name: "Максимальное количество участников",
        }

group/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404, redirect, render
from django.views import View
from django.views.generic import FormView, TemplateView

from core.forms import SearchForm
from group.forms import MeetupForm
from group.models import Meetup, MeetupParticipant
from theatres.models import TroupeMember
from users.models import add_experience


class GroupListView(FormView):
    template_name = "group/group_list.html"
    form_class = SearchForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        search_query = kwargs.get("search_query", None)

        if search_query:
            context["meetups"] = Meetup.meetups.meetup_search(search_query)
            context["current_search"] = search_query
        else:
            context["meetups"] = Meetup.meetups.meetup_list()

        return context

    def form_valid(self, form, **kwargs):
        return self.render_to_response(self.get_context_data(search_query=form.data["search"]))


class GroupDetailView(View):
    @staticmethod
    def get(request, **kwargs):
        template = "group/group_detail.html"

        meetup = get_object_or_404(Meetup.meetups.meetup_details(kwargs["id"]))
        user = request.user

        return render(
            request,
            template,
            {
                "meetup": meetup,
                "actors": TroupeMember.troupe_members.fetch(meetup.event.troupe_id).prefetch_related("profile"),
                "is_participant": user in [participant.user for participant in meetup.participants.all()],
            },
        )

    @staticmethod
    def post(request, **kwargs):
        user = request.user
        meetup = get_object_or_404(Meetup, pk=kwargs["id"])

        if "group_delete" in request.POST:
            if meetup.host == user:
                meetup.delete()
                add_experience(user.id, -2)
            return redirect("group:group_list")
        elif "group_join" in request.POST:
            if not meetup.is_participant(user):
                MeetupParticipant.objects.create(meetup=meetup, user=user)
                add_experience(meetup.host_id, 15)
        elif "group_leave" in request.POST:
            if meetup.is_participant(user):
                MeetupParticipant.objects.filter(user=user, meetup=meetup).delete()

        return redirect("group:group_detail", meetup.id)


class GroupCreateView(LoginRequiredMixin, TemplateView):
    template_name = "group/group_create.html"

    def get_context_data(self, **kwargs):
        form = MeetupForm()
        context = super().get_context_data(**kwargs)
        context["form"] = form
        return context

    @staticmethod
    def post(request):
        user = request.user

        form = MeetupForm(request.POST)
        meetup = form.save(commit=False)
        meetup.host = user
        meetup.save()
        add_experience(user.id, 5)

        return redirect("group:group_detail", meetup.id)

templates/group/group_create.html
{% extends "base.html" %}
{% block title %}Создать запрос{% endblock %}
{% block content %}
    <div class="container">
    <section style="margin-top: 6vh;margin-bottom: 10vh;">
        <div class="container multi-form-container-with-no-point mt-5">
        <div class="row d-flex justify-content-center align-items-center">
        <div class="col-md-6">
            <form id="regForm" action="." method="post">
                {% csrf_token %}
                <h1 id="register" class="header-text">Создание встречи </h1>
                <div class="all-steps" id="all-steps">
                    {% for field in form %}
                        <span class="step"></span>
                    {% endfor %}
                    <span class="step"></span>
                </div>

                {% for field in form %}
                    <div class="tab">
                        <h3>{{ field.label }}</h3>
                        <p>{{ field }}</p>
                        {% if not field.field.required %}
                            <p class="text-muted small"> Данное поле необязательно</p>
                        {% endif %}
                    </div>
                {% endfor %}

                <div class="thanks-message text-center" id="text-message"> <img src="https://i.imgur.com/O18mJ1K.png" width="100" class="mb-4">
                    <h3>Спасибо за создание новой встречи!</h3> <span>Пользуйтесь ей на здоровье! Никто не будет вам мешать.</span>
                </div>
                <div style="overflow:auto;" id="nextprevious">
                    <div style="float:right;"> <button type="button" id="prevBtn" onclick="nextPrev(-1)">Previous</button> <button type="button" id="nextBtn" onclick="nextPrev(1)">Next</button> </div>
                </div>
                </form>
        </div>
        </div>
        </div>
    </section>
    </div>
{% endblock %}

templates/group/group_detail.html
{% extends "base.html" %}
{% load static %}
{% block title %}Встреча{% endblock %}
{% block content %}
    <section>
        <div data-bss-parallax-bg="true" style="height: 600px;background-image: url({% if meetup.event.image %} {{ meetup.event.image.url}} {% else %} {% static '/img/NoneGroup400x300.jpg' %} {% endif %});background-position: center;background-size: cover;">
            <div class="container h-100">
                <div class="row h-100">
                    <div class="col-md-6 text-center text-md-start d-flex d-sm-flex d-md-flex justify-content-center align-items-center justify-content-md-start align-items-md-center justify-content-xl-center">
                        <form style="min-width: 320px;" action="." method="post">
                            {% csrf_token %}
                            <h1 class="text-uppercase fw-bold text-white">Встреча на постановке "{{ meetup.event.name }}"</h1>
                            {% if meetup.description %}
                                <p class="my-3 text-white">{{ meetup.description | truncatewords:10 }}</p>
                                <a class="btn btn-primary btn-lg menu_sub_link menu_linked" role="button" style="margin-top: 9px;" data-goto=".description">Описание</a>
                            {% endif %}
                            <a class="btn btn-primary btn-lg menu_sub_link menu_linked" type="button" style="margin-top: 9px;" data-goto=".event">Информация о постановке</a>
                            <a class="btn btn-primary btn-lg menu_sub_link menu_linked" type="button" style="margin-top: 9px;" data-goto=".groups">Участники</a>
                            {% if request.user.id != meetup.host_id %}
                                {% if not is_participant and meetup.participants_limit != meetup.participants_count %}
                                    <button class="btn btn-primary btn-lg" name="group_join" style="margin-top: 9px;" type="submit">Присоединиться к встрече</button>
                                {% elif meetup.participants_count != meetup.participants_limit %}
                                    <button class="btn btn-primary btn-lg" name="group_leave" style="margin-top: 9px;" type="submit">Покинуть встречу</button>
                                {% endif %}
                            {% else %}
                                <button class="btn btn-danger btn-lg" name="group_delete" style="margin-top: 9px;" type="submit">Удалить встречу</button>
                            {% endif %}
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <section>
        <div class="container py-4 py-xl-5">
            <div class="text-center text-white-50 bg-primary border rounded border-0 p-3">
                <div class="row row-cols-2 row-cols-md-3">
                    <div class="col">
                        <div class="p-3">
                            {% if meetup.host_id != request.user.id %}
                                <a href="{% url 'users:users_detail' meetup.host_id %}">
                                    <h4 class="display-5 fw-bold text-white mb-0"><i class="far fa-user"></i>{{ meetup.host }}</h4>
                                </a>
                            {% else %}
                                <a href="{% url 'users:profile' %}" >
                                    <h4 class="display-5 fw-bold text-white mb-0"><i class="far fa-user"></i>{{ meetup.host }}</h4>
                                </a>
                            {% endif %}
                            <p class="mb-0">Организатор</p>
                        </div>
                    </div>
                    <div class="col">
                        <div class="p-3">
                            <h4 class="display-5 fw-bold text-white mb-0"><i class="far fa-address-book"></i>{{ meetup.participants_count }}/{% if meetup.participants_limit %} {{ meetup.participants_limit }} {% else %}∞ {% endif %}</h4>
                            <p class="mb-0">Количество участников</p>
                        </div>
                    </div>
                    <div class="col">
                        <div class="p-3">
                            <h4 class="display-5 fw-bold text-white mb-0"><i class="fas fa-clock"></i>{{ meetup.start|date:'d.m.Y G:i' }}</h4>
                            <p class="mb-0">Время встречи</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <section>
        <div class="hobbies group events" style="padding-right: 15vh;padding-left: 15vh;padding-top: 0vh;padding-bottom: 4vh;">
            {% include 'includes/description_block.html' with description=meetup.description only %}
            <h2 class="text-center event mb-3">Постановка</h2>
            <h4 class="text-center">Краткая информация</h4>
            <div class="container py-5">
                <div class="row row-cols-1 row-cols-md-2 mx-auto" style="max-width: 900px;">
                    <div class="col mb-5">
                        {% if meetup.event.image %}
                            <img class="rounded img-fluid shadow" src="{{ meetup.event.get_image_400x300.url}}">
                        {% else %}
                            <img class="rounded img-fluid shadow" src="{% static 'img/NoneEvent400x300.jpg' %}">
                        {% endif %}
                    </div>
                    <div class="col d-md-flex align-items-md-end align-items-lg-center mb-5">
                        <div>
                            <h5 class="fw-bold">{{ meetup.event.name }}</h5>
                            {% if meetup.event.description %}
                                <p>{{ meetup.event.description | truncatewords:10 }}</p>
                            {% endif %}
                            <a href="{% url 'theatres:events_detail' meetup.event.id %}" class="btn btn-primary shadow" type="button">Подробнее</a>
                        </div>
                    </div>
                </div>
            </div>
            <h4 class="text-center">Место проведения</h4>
            <div class="container py-5">
                <div class="row row-cols-1 row-cols-md-2 mx-auto" style="max-width: 900px;">
                    <div class="col mb-5">
                        {% if meetup.event.theatre.image %}
                            <img class="rounded img-fluid shadow" src="{{ meetup.event.theatre.get_image_400x300.url}}">
                        {% else %}
                            <img class="rounded img-fluid shadow" src="{% static 'img/NoneTheatre400x300.jpg' %}">
                        {% endif %}
                    </div>
                    <div class="col d-md-flex align-items-md-end align-items-lg-center mb-5">
                        {% include 'includes/theatre_block.html' with theatre=meetup.event.theatre only %}
                    </div>
                </div>
            </div>
            {% if actors %}
                {% include 'includes/actors_block.html' with actors=actors only %}
            {% endif %}
        </div>
        <div class="hobbies group groups" style="padding-right: 15vh;padding-left: 15vh;padding-top: 0vh;padding-bottom: 4vh;">
            <h2 class="text-center">Участники</h2>
            <div class="album py-5">
            <div class="container">
            {% if meetup.participants.exists %}
                <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
                {% for user in meetup.participants.all %}
                <div class="col">
                    <div class="card shadow sm text-center">
                        <div class="col mb-5 ">
                            {% if user.user.id != request.user.id %}
                                <a href="{% url 'users:users_detail' user.user.user_profile.id %}"><img class="rounded img-fluid shadow" style="border:2px solid {{ user.user.user_profile.rank.color }}" src="{% if user.user.user_profile.image %} {{ user.user.user_profile.get_image_400x300.url }} {% else %} {% static '/img/NoneUser400x300.jpg' %} {% endif %}"></a>
                            {% else %}
                                <a href="{% url 'users:profile' %}"><img class="rounded img-fluid shadow" style="border:2px solid {{ user.user.user_profile.rank.color }}" src="{% if user.user.user_profile.image %} {{ user.user.user_profile.get_image_400x300.url }} {% else %} {% static '/img/
                                  User400x300.jpg' %} {% endif %}"></a>
                            {% endif %}
                        </div>
                        <div class="col d-md-flex mx-auto align-items-md-end align-items-lg-center mb-2">
                            <div>
                                <h5 class="fw-bold">{{  user.user.user_profile.first_name }} {{  user.user.user_profile.last_name }} ({{  user.user.username }})</h5>
                                {% if user.user.user_profile.description %}
                                    <p>{{ user.user.user_profile.description }}</p>
                                {% else %}
                                    <p class="text-muted">Описание отсутствует</p>
                                {% endif %}
                                {% if user.user.email %}
                                    <p class="text-muted mb-4"><i class="fa fa-envelope"></i>&nbsp;{{ user.user.email }}</p>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
                </div>
            {% else %}
                <h4>Участники отсутствуют.</h4>
            {% endif %}
            </div>
            </div>
        </div>
    </section>
{% endblock %}

templates/group/group_list.html
{% extends "base.html" %}
{% block title %}Встречи{% endblock %}
{% load static %}
{% block content %}
    <section>
        <div class="container py-5">
            <div class="row mb-4 mb-lg-5">
                <div class="col-md-8 col-xl-6 text-center mx-auto">
                    <h3 class="fw-bold">Список встреч</h3>
                    <form class="d-flex justify-content-center flex-wrap my-2" method="post" action=".">
                        {% csrf_token %}
                        <div class="my-2"><input class="form-control" type="text" name="search" placeholder="Название постановки" value="{{ current_search }}"></div>
                        <div class="my-2"><button class="btn btn-primary ms-sm-2" type="submit">Поиск</button></div>
                    </form>
                </div>
            </div>
            {% for meetup in meetups %}
                <div class="row row-cols-1 row-cols-md-2 mx-auto" style="max-width: 900px;">
                    <div class="col mb-5">
                        {% if meetup.event.image %}
                            <img class="rounded img-fluid shadow" src="{{ meetup.event.get_image_400x300.url}}">
                        {% else %}
                            <img class="rounded img-fluid shadow" src="{% static 'img/NoneGroup400x300.jpg' %}">
                        {% endif %}
                    </div>
                    <div class="col d-md-flex align-items-md-end align-items-lg-center mb-5">
                        <div>
                            <h5 class="fw-bold">Встреча на постановке "{{ meetup.event.name }}"</h5>
                            {% if meetup.description %}
                                <p>{{ meetup.description }}</p>
                            {% endif %}
                            <p class="text-muted mb-4"><i class="fas fa-map-marker-alt" style="padding-right: 8px;"></i>{{ meetup.event.theatre.location.query }}<br>
                            <i class="fa fa-user" style="padding-right: 8px;" aria-hidden="true"></i>Организатор: {% if meetup.host_id != request.user.id %}<a href="{% url 'users:users_detail' meetup.host_id %}" >{{meetup.host}}</a> {% else %} <a href="{% url 'users:profile' %}" >{{meetup.host}}</a> {% endif %}<br>
                            <i class="fa fa-address-book" style="padding-right: 8px;" aria-hidden="true"></i>Количество участников: {{ meetup.participants_count }}/{% if meetup.participants_limit %} {{ meetup.participants_limit }} {% else %}∞ {% endif %}<br>
                            <i class="fa fa-clock" style="padding-right: 8px;" aria-hidden="true"></i>Время проведения: {{ meetup.start }}</p>
                            <a href="{% url 'group:group_detail' meetup.id %}" class="btn btn-primary shadow" type="button">Подробнее</a>
                        </div>
                    </div>
                </div>
            {% empty %}
                <h3 class="fw-bold text-center">Встречи отсутствуют</h3>
            {% endfor %}
        <section class="py-4 py-xl-5">
            <div class="container">
                <div class="text-white bg-dark border rounded border-0 p-4 p-md-5">
                    <h2 class="fw-bold text-white mb-3">Хотите найти людей для посещения постановки?</h2>
                    <p class="mb-4">Ну так сделайте свою встречу и найдите их!</p>
                    <a class="btn btn-primary btn-lg me-2" role="button" href="{% url 'group:group_create' %}">Приступить к созданию</a>
                </div>
            </div>
        </section>
    </section>
{% endblock %}